model_name: distilbert-base-uncased
dataset_name: cornell-movie-review-data/rotten_tomatoes
wandb_project: LAB3-Transformers
run_name: distilbert-ex2
lora_args: 
  lora: True                         #se lora è attivo oppure no True, False
  rank: 16                            #rango delle matrici        8, 16
  alpha: 64                           #peso delle matrici        32, 64
training_args:
  learning_rate: 0.00005
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 3
  weight_decay: 0.01
  gradient_accumulation_steps: 2
  fp16: false
