seed: 99

device: cuda

data:
  batch_size: 128
  validation_split: 0.2
  num_workers: 4
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.2010]

model:
  path: "models/cifar10_Autoencoder.pth"  #"models/cifar10_CNN.pth", "models/cifar10_CNNplus.pth", "models/cifar10_Autoencoder.pth"

train:
  criterion: "MSELoss"                #per le cnn "CrossEntropyLoss" per gli autoencoder "MSELoss"
  optimizer: "Adam"
  criterion_params: {"reduction":"none"}                       #null per le cnn, {"reduction":"none"} per gli autoencoder
  lr: 0.0001
  epochs: 200
  scheduler: "CosineAnnealingLR"

logging:
  project_name: "Lab4-OOD_Detection"
