seed: 99

device: auto

data:
  batch_size: 128
  validation_split: 20
  num_workers: 2
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.2010]

model:
  path: "models/Autoencoder.pth"          #"models/cifar10_CNN.pth", "models/cifar10_CNNplus.pth", "models/cifar10_Autoencoder.pth"
  
setup:
  criterion: "MSELoss"           #per le cnn "CrossEntropyLoss" per gli autoencoder "MSELoss"
  optimizer: "Adam"
  criterion_params: {"reduction":"none"}                       #null per le cnn, {"reduction":"none"} per gli autoencoder
  lr: 0.0001
  epochs: 1                          #cnnplus:50, cnn:200, autoencoder:200
  scheduler: "CosineAnnealingLR"

fgsm:
  epsilons_cnn: [0.0, 0.01, 0.03, 0.05]
  epsilons_ae: [0.0] #, 0.01, 0.03, 0.05]
  train_epsilon: 0.03

logging:
  project_name: "Lab4-OOD_Detection"
