#Esperimento 1.3: CNN con e senza connessioni residuali su CIFAR-10
seed: 42 

data:
  batch_size: 128
  validation_split: 20  #Percentuale che definisce la grandezza del validation set
  num_workers: 4

model:
  type: "CNN"
  params:
    block_type: "basic"
    layers: 3  #Parametro che verrà sovrascritto in esecuzione (prove su profofndità)
    num_classes: 10
    residual: false  #Parametro che verrà sovrascritto in esecuzione (prove su connessioni residuali)
    zero_init_residual: true

training:
  epochs: 100
  criterion: "CrossEntropyLoss"
  optimizer: "Adam"
  lr: 0.001
  scheduler: "CosineAnnealingLR"

experiment:
  depths: [[2, 2, 2, 2], [3, 4, 6, 3], [5, 6, 8, 5]]   #Varie profondità di test

logging:
  project_name: "LAB1-CNN"
  log_gradients: false
