seed: 6

device: auto

data:
  batch_size: 128
  validation_split: 0.2
  num_workers: 4
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.2010]

fake_data:
  batch_size: 128
  num_workers: 4

model:
  path: "models/CNNplus.pth"           #"models/CNN.pth", "models/CNNplus.pth", "models/Autoencoder.pth"
  temps: [1000.0]                   #test con più temperature

train:
  criterion: "CrossEntropyLoss"            #per le cnn "CrossEntropyLoss" per gli autoencoder "MSELoss"
  criterion_params: null   #per le cnn null mentre per gli autoencoder {"reduction":"none"}

logging:
  project_name: "Lab4-OOD_Detection"
